# name: Build and Deploy to Docker Hub



# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v4

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./Dockerfile
#         push: true
#         tags: kartiktummawar/timetravel:latest  

#     - name: Verify Pushed Image
#       run: docker pull kartiktummawar/timetravel:latest  


name: Build and Deploy to Docker Hub

on:
  push:
    branches: 
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kartiktummawar/timetravel:latest

    - name: Verify Pushed Image
      run: docker pull kartiktummawar/timetravel:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull kartiktummawar/timetravel:latest
          sudo docker stop timetravel || true
          sudo docker rmi timetravel || true
          sudo docker run --restart=always -d --name timetravel -p 3000:3000 --env connectionString= ${{ secrets.DB_URL }} --env ACCESS_TOKEN_SECRET= ${{ secrets.ACCESS_TOKEN }}  kartiktummawar/timetravel:latest